name: mino
channels:
  - pyg
  - pytorch
  - nvidia
  - anaconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - asttokens=3.0.0
  - blas=1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - certifi=2025.1.31
  - charset-normalizer=3.3.2
  - cuda-cudart=12.4.127
  - cuda-cupti=12.4.127
  - cuda-libraries=12.4.1
  - cuda-nvrtc=12.4.127
  - cuda-nvtx=12.4.127
  - cuda-opencl=12.8.90
  - cuda-runtime=12.4.1
  - cuda-version=12.8
  - ffmpeg=4.3
  - filelock=3.13.1
  - freetype=2.12.1
  - gmp=6.3.0
  - gmpy2=2.2.1
  - gnutls=3.6.15
  - idna=3.7
  - intel-openmp=2023.1.0
  - ipykernel=6.29.5
  - jedi=0.19.2
  - jinja2=3.1.5
  - jpeg=9e
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - lame=3.100
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libcublas=12.4.5.8
  - libcufft=11.2.1.3
  - libcufile=1.13.1.3
  - libcurand=10.3.9.90
  - libcusolver=11.6.1.9
  - libcusparse=12.3.1.170
  - libdeflate=1.22
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.4
  - libjpeg-turbo=2.0.0
  - libnpp=12.2.5.30
  - libnvfatbin=12.8.90
  - libnvjitlink=12.4.127
  - libnvjpeg=12.3.1.117
  - libpng=1.6.39
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - libtasn1=4.19.0
  - libtiff=4.5.1
  - libunistring=0.9.10
  - libuuid=1.41.5
  - libwebp-base=1.3.2
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - markupsafe=3.0.2
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - nettle=3.7.3
  - networkx=3.4.2
  - numpy=1.26.4
  - numpy-base=1.26.4
  - ocl-icd=2.3.2
  - openh264=2.1.1
  - openjpeg=2.5.2
  - openssl=3.0.16
  - packaging=24.2
  - parso=0.8.4
  - pexpect=4.9.0
  - pillow=11.1.0
  - pip=25.0
  - prompt_toolkit=3.0.43
  - ptyprocess=0.7.0
  - pygments=2.19.1
  - pysocks=1.7.1
  - python=3.10.16
  - python-dateutil=2.9.0post0
  - pytorch=2.4.0
  - pytorch-cluster=1.6.3
  - pytorch-cuda=12.4
  - pytorch-mutex=1.0
  - pytorch-scatter=2.1.2
  - pyyaml=6.0.2
  - readline=8.2
  - requests=2.32.3
  - setuptools=75.8.0
  - six=1.17.0
  - sqlite=3.45.3
  - sympy=1.13.3
  - tbb=2021.8.0
  - tk=8.6.14
  - torchaudio=2.4.0
  - torchtriton=3.0.0
  - torchvision=0.19.0
  - tornado=6.4.2
  - traitlets=5.14.3
  - typing_extensions=4.12.2
  - urllib3=2.3.0
  - wcwidth=0.2.13
  - wheel=0.45.1
  - xz=5.6.4
  - yaml=0.2.5
  - zeromq=4.3.5
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - absl-py==2.1.0
      - accelerate==1.6.0
      - addict==2.4.0
      - aiofiles==24.1.0
      - aiohappyeyeballs==2.5.0
      - aiohttp==3.11.13
      - aiosignal==1.3.2
      - anndata==0.11.3
      - annotated-types==0.7.0
      - anyio==4.9.0
      - array-api-compat==1.11.1
      - asciitree==0.3.3
      - async-timeout==5.0.1
      - attrs==25.1.0
      - backends==1.6.6
      - beartype==0.20.2
      - beautifulsoup4==4.14.2
      - bleach==6.2.0
      - blessed==1.22.0
      - blinker==1.9.0
      - cartopy==0.24.1
      - cftime==1.6.5
      - clean-fid==0.1.35
      - click==8.1.8
      - comm==0.2.2
      - configargparse==1.7.1
      - configmypy==0.2.0
      - contourpy==1.3.1
      - cupy-cuda12x==13.6.0
      - cycler==0.12.1
      - dash==3.2.0
      - debugpy==1.8.13
      - decorator==5.2.1
      - deepwave==0.0.23
      - defusedxml==0.7.1
      - diffusers==0.33.1
      - docker-pycreds==0.4.0
      - einops==0.8.1
      - exceptiongroup==1.2.2
      - executing==2.2.0
      - fastapi==0.115.12
      - fasteners==0.19
      - fastjsonschema==2.21.2
      - fastrlock==0.8.3
      - ffmpy==0.5.0
      - flask==3.1.2
      - fonttools==4.56.0
      - frozenlist==1.5.0
      - fsspec==2025.3.0
      - ftfy==6.3.1
      - geometric-kernels==0.3
      - geomstats==2.8.0
      - gitdb==4.0.12
      - gitpython==3.1.44
      - gpustat==1.1.1
      - gradio==5.25.0
      - gradio-client==1.8.0
      - greenlet==3.2.4
      - groovy==0.1.2
      - grpcio==1.70.0
      - gunicorn==23.0.0
      - h11==0.14.0
      - h5py==3.13.0
      - httpcore==1.0.8
      - httpx==0.28.1
      - huggingface-hub==0.30.2
      - imageio==2.27.0
      - importlib-metadata==8.6.1
      - ipython==8.34.0
      - ipywidgets==8.1.5
      - itsdangerous==2.2.0
      - joblib==1.4.2
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyterlab-pygments==0.3.0
      - jupyterlab-widgets==3.0.13
      - kappamodules==0.1.112
      - kiwisolver==1.4.8
      - lazy-loader==0.4
      - legacy-api-wrap==1.4.1
      - lightgbm==4.6.0
      - lightning-bolts==0.7.0
      - lightning-utilities==0.14.0
      - llvmlite==0.44.0
      - lxml==6.0.2
      - markdown==3.7
      - markdown-it-py==3.0.0
      - matplotlib==3.7.5
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - mistune==3.1.4
      - multidict==6.1.0
      - mypy-extensions==1.1.0
      - narwhals==2.7.0
      - natsort==8.4.0
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - netcdf4==1.7.3
      - neuraloperator==1.0.2
      - numba==0.61.0
      - numcodecs==0.13.1
      - nvidia-ml-py==13.580.82
      - nvidia-nccl-cu12==2.29.3
      - obspy==1.4.2
      - open3d==0.19.0
      - opt-einsum==3.4.0
      - orjson==3.10.16
      - pandas==2.3.3
      - pandocfilters==1.5.1
      - pastel==0.2.1
      - patsy==1.0.1
      - piq==0.8.0
      - platformdirs==4.3.6
      - plotly==6.3.1
      - pluggy==1.5.0
      - plum-dispatch==2.5.5
      - poethepoet==0.10.0
      - pot==0.9.5
      - potpourri3d==1.2.1
      - prompt-toolkit==3.0.50
      - propcache==0.3.0
      - protobuf==5.29.3
      - psutil==7.0.0
      - pure-eval==0.2.3
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pydub==0.25.1
      - pygmt==0.13.0
      - pynndescent==0.5.13
      - pyparsing==3.2.1
      - pyproj==3.7.1
      - pyquaternion==0.9.9
      - pyre-extensions==0.0.32
      - pyshp==2.3.1
      - pytest==8.3.5
      - pytest-asyncio==0.26.0
      - pytest-mock==3.14.0
      - python-multipart==0.0.20
      - pytorch-lightning==1.9.5
      - pytz==2025.1
      - pyzmq==26.2.1
      - referencing==0.36.2
      - regex==2024.11.6
      - retrying==1.4.2
      - rich==14.0.0
      - robust-laplacian==1.0.0
      - rpds-py==0.27.1
      - ruamel-yaml==0.18.10
      - ruamel-yaml-clib==0.2.12
      - ruff==0.11.5
      - safehttpx==0.1.6
      - safetensors==0.5.3
      - scanpy==1.11.0
      - scikit-image==0.22.0
      - scikit-learn==1.5.2
      - scipy==1.15.2
      - scprep==1.2.3
      - seaborn==0.13.2
      - semantic-version==2.10.0
      - sentry-sdk==2.22.0
      - session-info2==0.1.2
      - setproctitle==1.3.5
      - shapely==2.1.1
      - shellingham==1.5.4
      - skorch==0.8.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - soupsieve==2.8
      - spherical-harmonics-basis==0.0.2
      - sqlalchemy==1.4.54
      - stack-data==0.6.3
      - starlette==0.46.1
      - statsmodels==0.14.4
      - tabulate==0.9.0
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - tensorly==0.9.0
      - tensorly-torch==0.5.0
      - the-well==1.1.0
      - threadpoolctl==3.5.0
      - tifffile==2025.3.30
      - timm==1.0.15
      - tinycss2==1.4.0
      - tokenizers==0.21.1
      - tomli==2.2.1
      - tomlkit==0.13.2
      - torch-geometric==2.6.1
      - torch-harmonics==0.7.3
      - torchcde==0.2.5
      - torchcfm==1.0.5
      - torchdiffeq==0.2.5
      - torchdyn==1.0.6
      - torchmetrics==1.6.2
      - torchsde==0.2.6
      - torchtnt==0.2.4
      - tqdm==4.67.1
      - trampoline==0.1.2
      - transformers==4.51.2
      - typer==0.15.2
      - typing-inspect==0.9.0
      - tzdata==2025.1
      - umap-learn==0.5.7
      - uvicorn==0.34.0
      - wandb==0.19.8
      - webencodings==0.5.1
      - websockets==15.0.1
      - werkzeug==3.1.3
      - widgetsnbextension==4.0.13
      - xarray==2025.6.1
      - xgboost==3.1.3
      - yarl==1.18.3
      - zarr==2.18.3
      - zipp==3.21.0
prefix: /home/czou/anaconda3/envs/mino
